{
    'name': 'medicine company',
    'version': '1.2',
    'summary': 'medicine company',
    'sequence': -100,
    'author': 'Nadeemkhan',
    'description': """medicine company""",
    'category': 'Productivity',
    'website': 'https://www.odoo.com/app/invoicing',
    'license': 'LGPL-3',
    'depends': ['base', 'mail', 'web'],
    # 'assets': {
    #     'web.assets_backend': [
    #         '/My_company/static/src/js/main.js',
    #         '/My_company/static/src/js/dashboard.js',
    #     ],
    # },
    'data': [
        'security/ir.model.access.csv',
        'data/sale_seq.xml',
        'data/purchase_seq.xml',
        'data/medicine_seq.xml',
        'data/stock.delivery.xml',
        'data/mail_template_sale.xml',
        'data/mail_template_purchase.xml',
        'wizard/sale_order_wizard.xml',
        'views/main_menu.xml',
        'views/medicine.xml',
        'views/purchase_order.xml',
        'views/sale_order.xml',
        'views/customer.xml',
        'views/stock_delivery.xml',
        'views/supply.xml',
        'views/capsule.xml',
        'views/tablet.xml',
        'views/injection.xml',
        'views/ointment.xml',
        'views/drip.xml',
        'report/reports_action.xml',
        'report/report_sale_order.xml',
        'report/report_purchase_order.xml',
        'report/medicine_reports.xml',
    ],
    'installable': True,
    'application': True,
    'auto_Install': False,
}
